// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: full_type.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace Tensorflow
{

    [global::ProtoBuf.ProtoContract()]
    public partial class FullTypeDef : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"type_id")]
        public FullTypeId TypeId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"args")]
        public global::System.Collections.Generic.List<FullTypeDef> Args { get; } = new global::System.Collections.Generic.List<FullTypeDef>();

        [global::ProtoBuf.ProtoMember(3, Name = @"s")]
        [global::System.ComponentModel.DefaultValue("")]
        public string S { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public enum FullTypeId
    {
        [global::ProtoBuf.ProtoEnum(Name = @"TFT_UNSET")]
        TftUnset = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"TFT_VAR")]
        TftVar = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"TFT_ANY")]
        TftAny = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"TFT_PRODUCT")]
        TftProduct = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"TFT_CALLABLE")]
        TftCallable = 100,
        [global::ProtoBuf.ProtoEnum(Name = @"TFT_TENSOR")]
        TftTensor = 1000,
        [global::ProtoBuf.ProtoEnum(Name = @"TFT_ARRAY")]
        TftArray = 1001,
        [global::ProtoBuf.ProtoEnum(Name = @"TFT_DATASET")]
        TftDataset = 10102,
        [global::ProtoBuf.ProtoEnum(Name = @"TFT_BOOL")]
        TftBool = 200,
        [global::ProtoBuf.ProtoEnum(Name = @"TFT_UINT8")]
        TftUint8 = 201,
        [global::ProtoBuf.ProtoEnum(Name = @"TFT_UINT16")]
        TftUint16 = 202,
        [global::ProtoBuf.ProtoEnum(Name = @"TFT_UINT32")]
        TftUint32 = 203,
        [global::ProtoBuf.ProtoEnum(Name = @"TFT_UINT64")]
        TftUint64 = 204,
        [global::ProtoBuf.ProtoEnum(Name = @"TFT_INT8")]
        TftInt8 = 205,
        [global::ProtoBuf.ProtoEnum(Name = @"TFT_INT16")]
        TftInt16 = 206,
        [global::ProtoBuf.ProtoEnum(Name = @"TFT_INT32")]
        TftInt32 = 207,
        [global::ProtoBuf.ProtoEnum(Name = @"TFT_INT64")]
        TftInt64 = 208,
        [global::ProtoBuf.ProtoEnum(Name = @"TFT_HALF")]
        TftHalf = 209,
        [global::ProtoBuf.ProtoEnum(Name = @"TFT_FLOAT")]
        TftFloat = 210,
        [global::ProtoBuf.ProtoEnum(Name = @"TFT_DOUBLE")]
        TftDouble = 211,
        [global::ProtoBuf.ProtoEnum(Name = @"TFT_COMPLEX64")]
        TftComplex64 = 212,
        [global::ProtoBuf.ProtoEnum(Name = @"TFT_COMPLEX128")]
        TftComplex128 = 213,
        [global::ProtoBuf.ProtoEnum(Name = @"TFT_STRING")]
        TftString = 214,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
