// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: model.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace tensorflow.data.model
{

    [global::ProtoBuf.ProtoContract()]
    public partial class ModelProto : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"output")]
        public Node Output { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"id_counter")]
        public long IdCounter { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"collect_resource_usage")]
        public bool CollectResourceUsage { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public OptimizationParams optimization_params { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public partial class Node : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"id")]
            public long Id { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"name")]
            [global::System.ComponentModel.DefaultValue("")]
            public string Name { get; set; } = "";

            [global::ProtoBuf.ProtoMember(3, Name = @"autotune")]
            public bool Autotune { get; set; }

            [global::ProtoBuf.ProtoMember(4, Name = @"buffered_bytes")]
            public long BufferedBytes { get; set; }

            [global::ProtoBuf.ProtoMember(5, Name = @"buffered_elements")]
            public long BufferedElements { get; set; }

            [global::ProtoBuf.ProtoMember(6, Name = @"bytes_consumed")]
            public long BytesConsumed { get; set; }

            [global::ProtoBuf.ProtoMember(7, Name = @"bytes_produced")]
            public long BytesProduced { get; set; }

            [global::ProtoBuf.ProtoMember(8, Name = @"num_elements")]
            public long NumElements { get; set; }

            [global::ProtoBuf.ProtoMember(9, Name = @"processing_time")]
            public long ProcessingTime { get; set; }

            [global::ProtoBuf.ProtoMember(10, Name = @"record_metrics")]
            public bool RecordMetrics { get; set; }

            [global::ProtoBuf.ProtoMember(11, Name = @"parameters")]
            public global::System.Collections.Generic.List<Parameter> Parameters { get; } = new global::System.Collections.Generic.List<Parameter>();

            [global::ProtoBuf.ProtoMember(12, Name = @"input_processing_time_sum")]
            public double InputProcessingTimeSum { get; set; }

            [global::ProtoBuf.ProtoMember(13, Name = @"input_processing_time_count")]
            public long InputProcessingTimeCount { get; set; }

            [global::ProtoBuf.ProtoMember(14, Name = @"inputs")]
            public global::System.Collections.Generic.List<Node> Inputs { get; } = new global::System.Collections.Generic.List<Node>();

            [global::ProtoBuf.ProtoMember(15, Name = @"node_class")]
            public NodeClass NodeClass { get; set; }

            [global::ProtoBuf.ProtoMember(16, Name = @"ratio")]
            public double Ratio { get; set; }

            [global::ProtoBuf.ProtoMember(17, Name = @"memory_ratio")]
            public double MemoryRatio { get; set; }

            [global::ProtoBuf.ProtoContract()]
            public partial class Parameter : global::ProtoBuf.IExtensible
            {
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                [global::ProtoBuf.ProtoMember(1, Name = @"name")]
                [global::System.ComponentModel.DefaultValue("")]
                public string Name { get; set; } = "";

                [global::ProtoBuf.ProtoMember(2, Name = @"value")]
                public double Value { get; set; }

                [global::ProtoBuf.ProtoMember(3, Name = @"state_value")]
                public double StateValue { get; set; }

                [global::ProtoBuf.ProtoMember(4, Name = @"min")]
                public double Min { get; set; }

                [global::ProtoBuf.ProtoMember(5, Name = @"max")]
                public double Max { get; set; }

                [global::ProtoBuf.ProtoMember(6, Name = @"tunable")]
                public bool Tunable { get; set; }

            }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class OptimizationParams : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"algorithm")]
            public AutotuneAlgorithm Algorithm { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"cpu_budget")]
            public long CpuBudget { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"ram_budget")]
            public long RamBudget { get; set; }

            [global::ProtoBuf.ProtoMember(4, Name = @"model_input_time")]
            public double ModelInputTime { get; set; }

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public enum NodeClass
    {
        [global::ProtoBuf.ProtoEnum(Name = @"UNKNOWN")]
        Unknown = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"INTERLEAVE_MANY")]
        InterleaveMany = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"ASYNC_INTERLEAVE_MANY")]
        AsyncInterleaveMany = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"KNOWN_RATIO")]
        KnownRatio = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"ASYNC_KNOWN_RATIO")]
        AsyncKnownRatio = 4,
        [global::ProtoBuf.ProtoEnum(Name = @"UNKNOWN_RATIO")]
        UnknownRatio = 5,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum AutotuneAlgorithm
    {
        [global::ProtoBuf.ProtoEnum(Name = @"HILL_CLIMB")]
        HillClimb = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"GRADIENT_DESCENT")]
        GradientDescent = 1,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
