// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: node_def.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace Tensorflow
{

    [global::ProtoBuf.ProtoContract()]
    public partial class NodeDef : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"op")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Op { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"input")]
        public global::System.Collections.Generic.List<string> Inputs { get; } = new global::System.Collections.Generic.List<string>();

        [global::ProtoBuf.ProtoMember(4, Name = @"device")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Device { get; set; } = "";

        [global::ProtoBuf.ProtoMember(5, Name = @"attr")]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<string, AttrValue> Attrs { get; } = new global::System.Collections.Generic.Dictionary<string, AttrValue>();

        [global::ProtoBuf.ProtoMember(6)]
        public ExperimentalDebugInfo experimental_debug_info { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public partial class ExperimentalDebugInfo : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"original_node_names")]
            public global::System.Collections.Generic.List<string> OriginalNodeNames { get; } = new global::System.Collections.Generic.List<string>();

            [global::ProtoBuf.ProtoMember(2, Name = @"original_func_names")]
            public global::System.Collections.Generic.List<string> OriginalFuncNames { get; } = new global::System.Collections.Generic.List<string>();

        }

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
